/* Instruments */
import {
  apiKeyAddSlice,
  apiKeyListSlice,
  dataFileAddSlice,
  dataFileListSlice,
  experimentAddSlice,
  experimentDetailSlice,
  experimentListSlice,
  experimentUpdateSlice,
  jobDetailSlice,
  stripeCheckoutSlice,
  modelAddSlice,
  modelDetailSlice,
  modelListSlice,
  transactionsSummarySlice,
  userSlice,
} from "./slices";

export const reducer = {
  user: userSlice.reducer,
  dataFileAdd: dataFileAddSlice.reducer,
  dataFileList: dataFileListSlice.reducer,
  modelAdd: modelAddSlice.reducer,
  modelList: modelListSlice.reducer,
  modelDetail: modelDetailSlice.reducer,
  experimentAdd: experimentAddSlice.reducer,
  experimentList: experimentListSlice.reducer,
  experimentDetail: experimentDetailSlice.reducer,
  experimentUpdate: experimentUpdateSlice.reducer,
  jobDetail: jobDetailSlice.reducer,
  apiKeyAdd: apiKeyAddSlice.reducer,
  apiKeyList: apiKeyListSlice.reducer,
  stripeCheckout: stripeCheckoutSlice.reducer,
  transactionsSummary: transactionsSummarySlice.reducer,
};
