package web3

import (
	"fmt"
	"math/rand"
)

var scienceAdjectives = []string{
	"atomic",
	"biological",
	"chemical",
	"dynamic",
	"electrical",
	"fissionable",
	"genetic",
	"hydrodynamic",
	"isotopic",
	"jurassic",
	"kinetic",
	"luminescent",
	"magnetic",
	"nuclear",
	"organic",
	"photonic",
	"quantum",
	"radiometric",
	"synthetic",
	"thermal",
	"ultraviolet",
	"volcanic",
	"waveform",
	"xerophilous",
	"yielding",
	"zoological",
	"acoustic",
	"barometric",
	"catalytic",
	"deterministic",
	"electromagnetic",
	"fluorescent",
	"geological",
	"holographic",
	"ionic",
	"jurisdictional",
	"kryptonian",
	"lithographic",
	"mechanical",
	"neurological",
	"optical",
	"probabilistic",
	"quantized",
	"radioactive",
	"systematic",
	"turbulent",
	"uniform",
	"volumetric",
	"wavelength",
	"xenobiotic",
	"yieldable",
	"zygotic",
	"anisotropic",
	"biometric",
	"computational",
	"diffusive",
	"elastic",
	"fractal",
	"gravitational",
	"heuristic",
	"inertial",
	"joule",
	"kinematic",
	"liquid",
	"molecular",
	"neuronal",
	"oscillatory",
	"polar",
	"quantifiable",
	"relativistic",
	"spatial",
	"topological",
	"universal",
	"variable",
	"wave-like",
	"xenomorphic",
	"yielding",
	"zoophytic",
	"adiabatic",
	"bionic",
	"chromatic",
	"dynamical",
	"exothermic",
	"ferromagnetic",
	"geodesic",
	"harmonic",
	"isochronous",
	"junctional",
	"kaleidoscopic",
	"laminar",
	"metamorphic",
	"nonlinear",
	"oscillating",
	"paramagnetic",
	"quantitative",
	"resonant",
	"statistical",
	"thermodynamic",
	"unidirectional",
	"viscous",
	"wave-particle",
	"xerographic",
	"yeasty",
	"zoogeographical",
}

var scienceNames = []string{
	"feynman",
	"bohr",
	"maxwell",
	"faraday",
	"edison",
	"tesla",
	"franklin",
	"mcClintock",
	"heisenberg",
	"mendeleev",
	"rutherford",
	"dirac",
	"röntgen",
	"goodall",
	"pauling",
	"lawrence",
	"fermi",
	"oppenheimer",
	"sagan",
	"hawking",
	"watson",
	"crick",
	"wilkins",
	"haber",
	"carson",
	"mendel",
	"turing",
	"berners-lee",
	"curie",
	"joliot-curie",
	"teller",
	"nobel",
	"brin",
	"page",
	"musk",
	"jobs",
	"gates",
	"korolev",
	"einstein",
	"hamilton",
	"hopper",
	"burnell",
	"rubin",
	"hubble",
	"goeppert-mayer",
	"meitner",
	"minkowski",
	"salam",
	"bose",
	"de broglie",
	"chandrasekhar",
	"gamow",
}

var scienceNouns = []string{
	"atoms",
	"molecules",
	"species",
	"galaxies",
	"neurons",
	"electrons",
	"quarks",
	"genomes",
	"black holes",
	"cells",
	"organisms",
	"asteroids",
	"protons",
	"elements",
	"proteins",
	"receptors",
	"chromosomes",
	"meteors",
	"neutrinos",
	"planets",
	"ions",
	"photons",
	"quasars",
	"leptons",
	"genes",
	"nucleotides",
	"amino acids",
	"DNA",
	"ribosomes",
	"mitochondria",
	"cytoplasm",
	"membranes",    // Boring
	"lysosomes",    // Not commonly known outside of cellular biology
	"golgi bodies", // Boring
	"nuclei",
	"endoplasmic reticulum", // Less known and perhaps less "cool" due to being quite abstract
	"vacuoles",
	"centrioles", // Not commonly known outside of cellular biology
	"cilia",      // Not commonly known outside of cellular biology
	"flagella",
	"axons",
	"dendrites",
	"synapses",
	"neurotransmitters",
	"antibodies",
	"antigens",
	"enzymes",
	"subatomic particles",
	"nuclei",
	"solar systems",
	"constellations",
	"supernovas",
	"white dwarfs",
	"red giants",
	"neutron stars",
	"spiral galaxies",
	"elliptical galaxies",
	"globular clusters", // May be perceived as less "cool" because it's a less familiar astronomical term
	"binary stars",
	"pulsars",
	"comets",
	"exoplanets",
	"dark matter",
	"dark energy",
	"quark stars", // Highly theoretical and thus could be considered obscure
	"gravity waves",
	"bosons",
	"fermions",
	"leptons",
	"mesons",
	"baryons",
	"hadrons",
	"gluons",
	"muons",
	"tau particles", // Not as commonly known as other particle types
	"neutrinos",
	"z bosons", // Lesser-known particle type
	"w bosons", // Lesser-known particle type
	"higgs boson",
	"strange quarks", // The names of specific quarks might be considered obscure
	"up quarks",
	"down quarks",
	"charm quarks",
	"top quarks",
	"bottom quarks",
	"antineutrinos",
	"positrons",
	"antineutrons",  // Lesser-known particle type
	"antiquarks",    // Lesser-known particle type
	"antiup quarks", // The names of specific antiquarks might be considered obscure
	"antidown quarks",
	"anticharm quarks",
	"antitop quarks",
	"antibottom quarks",
	"gluinos",    // Highly theoretical and thus could be considered obscure
	"gravitinos", // Highly theoretical and thus could be considered obscure
	"photinos",   // Highly theoretical and thus could be considered obscure
	"squarks",    // Highly theoretical and thus could be considered obscure
	"selectrons", // Highly theoretical and thus could be considered obscure
	"neutrinos",
	"winos",              // Highly theoretical and thus could be considered obscure
	"zinos",              // Highly theoretical and thus could be considered obscure
	"higgsinos",          // Highly theoretical and thus could be considered obscure
	"axinos",             // Highly theoretical and thus could be considered obscure
	"gravitons",          // Highly theoretical and thus could be considered obscure
	"dilatons",           // Highly theoretical and thus could be considered obscure
	"preons",             // Highly theoretical and thus could be considered obscure
	"magnetic monopoles", // Highly theoretical and thus could be considered obscure
	"tachyons",           // Highly theoretical and thus could be considered obscure
	"kaons",              // Lesser-known particle type
}

func GenerateTokenName() string {
	adj := scienceAdjectives[rand.Intn(len(scienceAdjectives))]
	name := scienceNames[rand.Intn(len(scienceNames))]
	noun := scienceNouns[rand.Intn(len(scienceNouns))]

	return fmt.Sprintf("%s %s %s", adj, name, noun)
}
