-- Seed tags table with predefined values
INSERT INTO tags (name, type) VALUES
('uploaded', 'autogenerated'),
('generated', 'autogenerated')
ON CONFLICT (name) DO NOTHING; -- This prevents duplication if the migration is run multiple times
