basic_settings:
  experiment_name: default
  protein_complex: inputs/target_protein.pdb
expert_settings:
  num_seqs: 8
  rm_aa: C
  mpnn_sampling_temp: 0.1
  use_solubleMPNN: true
  initial_guess: true
  chains_to_design: A
